upadte all scripts

diff --git a/setup b/setup
--- a/setup
+++ b/setup
@@ -21,13 +21,13 @@ DISTRO=$(get_distro)
 # Function to install packages based on the distribution
 install_packages() {
     case $DISTRO in
-        debian)
+        debian|ubuntu)
             sudo apt install "$@"
             ;;
         arch)
             sudo pacman -S --needed "$@"
             ;;
-        rocky)
+        rocky|fedora)
             sudo dnf install "$@"
             ;;
         *)
@@ -35,6 +35,11 @@ install_packages() {
             read -p "Press Enter to continue or Ctrl+C to exit..."
             ;;
     esac
+}
+
+# Check whether this system is a laptop (has a battery)
+is_laptop() {
+    ls /sys/class/power_supply/BAT* > /dev/null 2>&1
 }
 
 current_dir=$(pwd)
@@ -48,50 +53,40 @@ case $DISTRO in
         libpcre2-dev libpixman-1-dev libx11-xcb-dev libxcb1-dev libxcb-composite0-dev libxcb-damage0-dev \
         libxcb-dpms0-dev libxcb-glx0-dev libxcb-image0-dev libxcb-present-dev libxcb-randr0-dev libxcb-render0-dev \
         libxcb-render-util0-dev libxcb-shape0-dev libxcb-util-dev libxcb-xfixes0-dev libxext-dev meson ninja-build \
-        uthash-dev cmake libxft-dev libimlib2-dev libxinerama-dev libxcb-res0-dev alsa-utils
-        # Check if the system is a laptop
-        if [ -d "/sys/class/power_supply" ]; then
-            install_packages brightnessctl
-        fi
+        uthash-dev cmake alsa-utils rofi
         ;;
     arch)
         install_packages libx11 libxft libxinerama libxcb kitty feh mate-polkit flameshot dunst base-devel \
-        libconfig dbus libev libx11 libxext libgl libegl libepoxy meson pcre2 pixman uthash xcb-util-image \
-        xcb-util-renderutil xorgproto cmake libxft imlib2 libxinerama xcb-util xorg-xev xorg-xbacklight \
-        alsa-utils feh thunar-media-tags-plugin thunar-archive-plugin thunar-volman
-        # Check if the system is a laptop
-        if [ -d "/sys/class/power_supply" ]; then
-            install_packages brightnessctl
-        fi
+        libconfig dbus libev libxext libgl libegl libepoxy meson pcre2 pixman uthash xcb-util-image \
+        xcb-util-renderutil xorgproto cmake imlib2 xcb-util xorg-xev xorg-xbacklight \
+        alsa-utils thunar-media-tags-plugin thunar-archive-plugin thunar-volman rofi
         ;;
-    rocky)
-        install_packages libX11-devel libXft-devel imlib2-devel libXinerama-devel libxcb-devel kitty feh polkit \
-        flameshot dunst dbus-devel gcc git libconfig-devel libdrm-devel libev-devel libX11-devel libX11-xcb \
-        libXext-devel libxcb-devel libGL-devel libEGL-devel libepoxy-devel meson ninja-build pcre2-devel \
+    rocky|fedora)
+        install_packages libX11-devel libXft-devel imlib2-devel libXinerama-devel libxcb-devel kitty feh mate-polkit \
+        flameshot dunst dbus-devel gcc git libconfig-devel libdrm-devel libev-devel libX11-xcb \
+        libXext-devel libGL-devel libEGL-devel libepoxy-devel meson ninja-build pcre2-devel \
         pixman-devel uthash-devel xcb-util-image-devel xcb-util-renderutil-devel xorg-x11-proto-devel \
-        xcb-util-devel cmake libxft-devel libimlib2-devel libxinerama-devel libxcb-res0-devel alsa-utils
-        # Check if the system is a laptop
-        if [ -d "/sys/class/power_supply" ]; then
-            install_packages brightnessctl
-        fi
+        xcb-util-devel cmake alsa-utils rofi
         ;;
 esac
 
-# Check if the system is a laptop
-if [ -d "/sys/class/power_supply" ]; then
-    # System is likely a laptop
+# Laptop-only extras: brightness control tool and key bindings
+if is_laptop; then
     echo "Laptop detected. Installing brightnessctl and adding brightness controls to DWM config."
-    
-    # Install brightnessctl
-    install_brightnessctl
 
-    # Append new key bindings to config.def.h
-    sed -i '/{ MODKEY,                       XK_e,          spawn,                  SHCMD ("thunar")}, \/\/ open thunar file manager/a \
+    install_packages brightnessctl
+
+    # Append new key bindings to config.def.h (only once)
+    if ! grep -q "brightnessctl" config.def.h; then
+        sed -i '/{ MODKEY,                       XK_e,          spawn,                  SHCMD ("thunar")}, \/\/ open thunar file manager/a \
     { 0,                            0x1008ff03,    spawn,                  SHCMD ("brightnessctl s 10%-")}, // decrease backlight brightness\
     { 0,                            0x1008ff02,    spawn,                  SHCMD ("brightnessctl s +10%")}, // increase backlight brightness\
     { 0,                            0x1008ff8e,    spawn,                  SHCMD ("brightnessctl s 10%-")}, // decrease backlight brightness' config.def.h
-    
-    echo "Brightness controls added to DWM config."
+
+        echo "Brightness controls added to DWM config."
+    else
+        echo "Brightness controls already present in DWM config."
+    fi
 else
     echo "This doesn't appear to be a laptop. Skipping brightness control configuration."
 fi
@@ -102,20 +97,15 @@ sudo make clean install
 get_git_path() {
     # Check if GIT_PATH is already set
     if [ -z "$GIT_PATH" ]; then
-        read -p "Do you want to create a default location for git repositories? (y/n) " create_git_dir
-        if [[ $create_git_dir =~ ^[Yy]$ ]]; then
-            read -p "Enter the path for git repositories (default: $HOME/git): " git_path
-            GIT_PATH=$git_path
-            export GIT_PATH
-                
-            if [ ! -d "$GIT_PATH" ]; then
-                mkdir -p "$GIT_PATH"
-                echo "Created git directory at $GIT_PATH"
-            else
-                echo "Git directory already exists at $GIT_PATH"
-            fi
+        read -p "Enter the path for git repositories (default: $HOME/git): " git_path
+        GIT_PATH=${git_path:-$HOME/git}
+        export GIT_PATH
+
+        if [ ! -d "$GIT_PATH" ]; then
+            mkdir -p "$GIT_PATH"
+            echo "Created git directory at $GIT_PATH"
         else
-            echo "Skipping git directory creation."
+            echo "Git directory already exists at $GIT_PATH"
         fi
     else
         echo "GIT_PATH is already set to $GIT_PATH"
@@ -136,7 +126,7 @@ fi
 
 cd $current_dir
 
-# Ask user if they want to use picom files
+# Ask user if they want to install picom (FT-Labs fork, provides blur/rounding/animations)
 read -p "Do you want to install picom? (y/n) " install_picom
 
 if [[ $install_picom =~ ^[Yy]$ ]]; then
@@ -144,17 +134,17 @@ if [[ $install_picom =~ ^[Yy]$ ]]; then
 
     # Check if picom exists
     if ! command -v picom &> /dev/null; then
+        get_git_path
         if [ ! -d $GIT_PATH/picom ]; then
-            get_git_path
             if ! git clone https://github.com/FT-Labs/picom.git $GIT_PATH/picom; then
                 echo "Failed to clone the repository"
-                return 1
+                exit 1
             fi
         else
             echo "Repository already exists, skipping clone"
         fi
-        cd $GIT_PATH/picom || { echo "Failed to change directory to picom"; return 1; }
-        
+        cd $GIT_PATH/picom || { echo "Failed to change directory to picom"; exit 1; }
+
         case $DISTRO in
             debian|ubuntu)
                 install_packages libev-dev libxcb-present-dev
@@ -162,7 +152,7 @@ if [[ $install_picom =~ ^[Yy]$ ]]; then
             arch)
                 install_packages libev libxcb xcb-util-renderutil xcb-util-image
                 ;;
-            rocky)
+            rocky|fedora)
                 install_packages libev-devel libxcb-devel xcb-util-renderutil-devel xcb-util-image-devel
                 ;;
             *)
@@ -171,22 +161,23 @@ if [[ $install_picom =~ ^[Yy]$ ]]; then
                 read -p "Press Enter to continue or Ctrl+C to exit..."
                 ;;
         esac
-        
+
         # Build the project
         if ! meson setup --buildtype=release build; then
             echo "Meson setup failed"
-            return 1
+            exit 1
         fi
         if ! ninja -C build; then
             echo "Ninja build failed"
-            return 1
+            exit 1
         fi
         # Install the built binary
         if ! sudo ninja -C build install; then
             echo "Failed to install the built binary"
-            return 1
+            exit 1
         fi
-        echo "Picom animations installed successfully"
+        echo "Picom (FT-Labs) installed successfully"
+        echo "The macOS Tahoe glass settings live in ~/.config/picom/picom.conf (from the dotconfig repo)."
         cd $current_dir
     else
         echo "picom is already installed"
@@ -211,7 +202,7 @@ if [[ $install_lightdm =~ ^[Yy]$ ]]; then
             install_packages lightdm lightdm-gtk-greeter
             sudo systemctl enable lightdm
             ;;
-        rocky)
+        rocky|fedora)
             install_packages lightdm lightdm-gtk
             sudo systemctl enable lightdm
             sudo systemctl set-default graphical.target
